### ISSUE TITLE
Support for Gatsby v4

### ISSUE THREAD

**Issue by smyrick** [CollierCZ/gatsby-transformer-gitinfo#142]
The current `peerDependencies` lock this to Gatsby v3. We could make this a optional version `3 || 4` to allow for other major version

https://github.com/CollierCZ/gatsby-transformer-gitinfo/blob/cdf4910da84f5f76da9464a90c9d21348680ae5c/package.json#L27-L29

Error
```
npm ERR! Found: gatsby@4.21.1
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^4.6.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^3.0.0" from @colliercz/gatsby-transformer-gitinfo@1.1.0
npm ERR! node_modules/@colliercz/gatsby-transformer-gitinfo
npm ERR!   @colliercz/gatsby-transformer-gitinfo@"1.1.0" from the root project
```

**Comment by CollierCZ** [comment]
Should be available in version 1.3.0. Let me know if you run into any issues.
